version: '3.3'
services:
  backend:
    environment:
      - SERVER_HOST=http://${DOMAIN}
  celeryworker:
    environment:
      - RUN=celery worker -A app.worker -l info -Q main-queue -c 1
      - SERVER_HOST=http://${DOMAIN}
