"""First revision

Revision ID: d4867f3a4c0a
Revises: 
Create Date: 2019-04-17 13:53:32.978401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd4867f3a4c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('wants_emails', sa.Boolean(), nullable=False),
      sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    op.create_table('prayers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    )

    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ccbid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=385), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.Column('member_since', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    )

    partners_table = op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ccbid', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=385), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(partners_table,
    [
        {'id': 1,
        'ccbid': 375,
        'type': 'Supported Worker',
        'name': 'Kyle Nieber',
        'email': 'kyle.nieber@gmail.com',
        'description': 'The Niebers work somewhere',
        'image_url': 'https://ccbchurch.s3.amazonaws.com/33321/pics/ipic_375?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIASIGAHNLGZZR43C3F%2F20200220%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200220T144111Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=7a21e792f94da152b0ce177edf0695b655b0976c39105aff156b3701f9f6b7d1',
        'location': 'NE Asia'
        },
        {'id': 2,
        'ccbid': 59,
        'type': 'Strategic Partner',
        'name': 'Chris Phillips',
        'email': 'chris@email.com',
        'description': 'The Phillips work somewhere',
        'image_url': 'https://ccbchurch.s3.amazonaws.com/33321/pics/ipic_59?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIASIGAHNLGZZR43C3F%2F20200220%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200220T143959Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=1cac8b860a9e25a82a5038a72eddee6316dd5a3dc079734cf1bdf1aafa77a181',
        'location': 'NE Asia'
        },
        {'id': 3,
        'ccbid': 570,
        'type': 'Strategic Partner',
        'name': 'Mac Stiles',
        'email': 'mac@email.com',
        'description': 'The Stiles work somewhere',
        'image_url': 'https://ccbchurch.s3.amazonaws.com/33321/pics/ipic_570?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIASIGAHNLGZZR43C3F%2F20200220%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200220T143106Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=1bf9a14f1547bc192596574f34f693ad4f9449dd17fdf77d046fb4bd20319895',
        'location': 'Erbil, Iraq'
        },
        {'id': 4,
        'ccbid': 1051,
        'type': 'Supported Worker',
        'name': 'Cory McArtor',
        'email': 'csmcartor@gmail.com',
        'description': 'The McArtors work somewhere',
        'image_url': 'https://ccbchurch.s3.amazonaws.com/33321/pics/ipic_1051?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIASIGAHNLGZZR43C3F%2F20200220%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200220T143856Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=774067008eb4bc1537881dcf2286b63da6ce837a9b6db04f3570df93c0d5022b',
        'location': 'Erbil, Iraq'
        },
    ]
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('prayers')
    op.drop_table('members')
    op.drop_table('partners')
    # ### end Alembic commands ###
